### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by tswast** [WeAllCode/website#854]
Without a license file, Googlers are forbidden from submitting patches to this project. See the policy documents here: https://opensource.google/docs/patching/#forbidden

Some resources for picking a license: https://choosealicense.com/

Django is licensed as BSD (https://github.com/django/django/blob/master/LICENSE) so that may be a natural choice.

**Comment by karbassi** [comment]
Thanks @tswast for bringing this to my attention. Fixed.
